# Generated by Django 3.2.5 on 2022-09-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='number',
        ),
    ]
