# Generated by Django 3.2.5 on 2022-09-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_customuser_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
